### ISSUE TITLE
Documentation link is dead !

### ISSUE THREAD

**Issue by dangminhbk** [codific/mvc567#28]
https://mvc567.com/documentation/getting-started/development-environment
Please check that.

**Comment by gsk567** [comment]
The documentation has been moved on GitHub environment. Please find the documentation on https://codific.github.io/mvc567/

**Comment by dangminhbk** [comment]
@gsk567 thanks you! But Admin Authenticator Generator is still missing.

**Comment by gsk567** [comment]
In the current version of Codific.Mvc567 the third factor is removed. In case you want to implement your own and you need authenticator generator - this is the code of the vue component:

`
Vue.component('admin-authenticator-generator', {
    data: function () {
        return {
            issuer: 'mvc567',
            account: 'example@mvc567.com',
            generated: false,
            authenticatorHash: '',
            cookieFormat: '',
            secretIndexes: '',
            qrCodeSize: 180,
        };
    },
    components: {
        'qrcode-vue': QrcodeVue
    },
    computed: {
        authenticatorUriFormat() {
            return `otpauth://totp/${this.issuer}:${this.account}?secret=${this.authenticatorHash}&issuer=${this.issuer}&digits=6`;
        }
    },
    methods: {
        generate() {
            this.authenticatorHash = this.generateSecretKey(20);
            this.cookieFormat = this.generateRandomCookieFormat();
            this.secretIndexes = this.generateRandomIndexes();
            this.generated = true;
        },
        generateRandomIndexes() {
            let indexes = [];
            for (let i = 0; i < 6; i++) {
                indexes.push(Math.floor((Math.random() * 31) + 1));
            }

            return indexes.join(',');
        },
        generateRandomCookieFormat() {
            let result = '';
            let characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ_abcdefghijklmnopqrstuvwxyz_0123456789';
            let charactersLength = characters.length;
            let length = 64;
            let index1 = Math.floor((Math.random() * 30) + 1);
            let index2 = Math.floor((Math.random() * 30) + 33);
            for (let i = 0; i < length; i++) {
                result += characters.charAt(Math.floor(Math.random() * charactersLength));
                if (i == index1) {
                    result += "{0}";
                }
                if (i == index2) {
                    result += "{1}";
                }
            }
            return result;
        },
        randomBytes(size) {
            const crypto = window.crypto || window.msCrypto;

            if (!crypto || typeof crypto.getRandomValues !== 'function') {
                throw new Error(
                    'Unable to load crypto module. You may be on an older browser'
                );
            }

            if (size > 65536) {
                throw new Error('Requested size of random bytes is too large');
            }

            if (size < 1) {
                throw new Error('Requested size must be more than 0');
            }

            const rawBytes = new Uint8Array(size);
            crypto.getRandomValues(rawBytes);
            let binary = '';
            for (let i = 0; i < size; i++) {
                binary += String.fromCharCode(rawBytes[i]);
            }

            return window.btoa(binary);
        },
        generateSecretKey(length) {
            if (!length || length < 1) {
                return '';
            }

            return this.encodeKey(this.randomBytes(length)
                .toString('base64')
                .slice(0, length));
        },
        encodeKey(secret) {
            return base32.encode(secret)
                .toString()
                .replace(/=/g, '');
        }
    },
    template: `
        <div class="row">
            <div class="col-md-6 col-12">
                <div class="card p-4">
                    <form @submit.prevent="generate">
                        <div class="form-group">
                            <label>Issuer:</label>
                            <input v-model="issuer" type="text" class="form-control p-2 border-secondary" placeholder="Issuer" />
                        </div>
                        <div class="form-group">
                            <label>Account:</label>
                            <input v-model="account" type="email" class="form-control p-2 border-secondary" placeholder="Account" />
                        </div>
                        <p class="text-small text-danger font-weight-bold">All generated data is available only on your client side. By clicking the button Generate no sensitive data will be sent accross internet.</p>
                        <div class="form-group d-flex">
                            <button type="submit" class="btn btn-primary submit-btn btn-block w-auto ml-auto mr-0">Generate</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md-6 col-12" v-if="generated == true">
                <div class="card p-4">
                    <div class="authenticator-generator-result">
                    <div class="mb-2">
                        <h5>Authenticator QR Code:</h5>
                        <qrcode-vue :value="authenticatorUriFormat" :size="qrCodeSize" level="H"></qrcode-vue>
                    </div>
                    <div class="mb-2">
                        <h5>Configuration JSON object:</h5>
                        <pre class="default-code-pre">"AdminLoginAuthenticator": {
  "SecretKey": "{{authenticatorHash}}",
  "CookieFormat": "{{cookieFormat}}",
  "SecretIndexes": "{{secretIndexes}}",
  "ShowForTestPurposes": false
}</pre>
                    </div>
                </div>
            </div>
        </div>
`
});
`
